Document: sdrdaemon
Title: Debian sdrdaemon Manual
Author: <insert document author here>
Abstract: This manual describes what sdrdaemon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sdrdaemon/sdrdaemon.sgml.gz

Format: postscript
Files: /usr/share/doc/sdrdaemon/sdrdaemon.ps.gz

Format: text
Files: /usr/share/doc/sdrdaemon/sdrdaemon.text.gz

Format: HTML
Index: /usr/share/doc/sdrdaemon/html/index.html
Files: /usr/share/doc/sdrdaemon/html/*.html
