INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_FECLIB "libfeclib")

FIND_PATH(FECLIB_INCLUDE_DIR
    NAMES feclib/fec.h
    HINTS ${PC_FECLIB_INCLUDE_DIR}
    ${CMAKE_INSTALL_PREFIX}/include
    ${LIBFECLIB_INSTALL_PREFIX}/include
    PATHS
    /usr/local/include
    /usr/include
)

FIND_LIBRARY(FECLIB_LIBRARIES
    NAMES feclib libfeclib
    HINTS ${PC_FECLIB_LIBDIR}
    ${CMAKE_INSTALL_PREFIX}/lib
    ${CMAKE_INSTALL_PREFIX}/lib64
    PATHS
    ${FECLIB_INCLUDE_DIR}/../lib
    /usr/local/lib
    /usr/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FECLIB DEFAULT_MSG FECLIB_LIBRARIES FECLIB_INCLUDE_DIR)
MARK_AS_ADVANCED(FECLIB_LIBRARIES FECLIB_INCLUDE_DIR)
